# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE", "business_mgmt_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE_TEST", "business_mgmt_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE_PRODUCTION", "business_mgmt_production") %>
  username: <%= ENV.fetch("PGUSER_PRODUCTION", ENV.fetch("PGUSER", "postgres")) %>
  password: <%= ENV.fetch("PGPASSWORD_PRODUCTION", ENV.fetch("PGPASSWORD", "")) %>
  host: <%= ENV.fetch("PGHOST_PRODUCTION", ENV.fetch("PGHOST", "localhost")) %>
  port: <%= ENV.fetch("PGPORT_PRODUCTION", ENV.fetch("PGPORT", 5432)) %>